spring: 
  profiles:
    active: dev

---
spring:
  profiles: dev
      
server:
  tomcat:
      uri-encoding: UTF-8
      
management:
  security:
    enabled: false
  
eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance: 
    instance-id: provider-realaccount-dev
    prefer-ip-address: true
  
logging:
  config: classpath:logback-boot.xml
  
values:
  name: aaabbbcccddd  
  
---
spring:
  profiles: test
      
server:
  tomcat:
      uri-encoding: UTF-8
      
management:
  security:
    enabled: false
  
eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance: 
    instance-id: provider-realaccount-test
    prefer-ip-address: true
  
logging:
  config: classpath:logback-boot.xml
    
---
spring:
  profiles: prod
      
server:
  tomcat:
      uri-encoding: UTF-8
      
management:
  security:
    enabled: false
  
eureka:
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:7001/eureka/
  instance: 
    instance-id: provider-realaccount-prod
    prefer-ip-address: true
  
logging:
  config: classpath:logback-boot.xml